import type { InstanceConfig } from './types'

export function defaultInstanceConfig(): InstanceConfig {
  return {
    id: '', name: '', engine_id: '', model_path: '', alias: '',
    lora_path: '', mmproj_path: '', lora_init_without_apply: false, lora_scaled: '',
    chat_template: '', chat_template_file: '', skip_chat_parsing: false,
    reasoning_format: '', reasoning_effort: '', reasoning: '',
    jinja: true, reasoning_budget: '', reasoning_budget_message: '',
    grammar_file: '', grammar: '',
    ctx_size: 0, ctx_size_auto: false, gpu_layers_auto: true, gpu_layers: 99,
    threads: 0, batch_size: 2048, ubatch_size: 512, parallel: -1,
    cont_batching: true, cache_prompt: true, threads_batch: 0,
    threads_http: -1, keep: 0, cache_reuse: 0, cache_ram: 8192,
    warmup: true, ctx_checkpoints: 32, checkpoint_min_step: 256,
    swa_full: false,
    rope_scaling: '', rope_scale: 0, rope_freq_base: 0, rope_freq_scale: 0,
    yarn_ext_factor: -1, yarn_attn_factor: -1, yarn_beta_slow: -1, yarn_beta_fast: -1, yarn_orig_ctx: 0,
    flash_attn: 'auto', moe_cpu_layers: 0, mlock: false,
    no_mmap: false, no_repack: false, numa: false, context_shift: false,
    perf: false, check_tensors: false, fit: false, fit_target: '', fit_ctx: 4096,
    kv_unified: false, cache_idle_slots: true, no_kv_offload: false,
    cache_type_k: '', cache_type_v: '',
    cache_type_draft_k: '', cache_type_draft_v: '',
    draft_model_path: '', draft_gpu_layers: 99, draft_tokens: 3,
    spec_draft_n_min: 0, spec_type: '',
    spec_draft_p_min: 0, spec_draft_p_split: 0.1, spec_draft_device: '',
    lookup_cache_static: '', lookup_cache_dynamic: '',
    spec_default: false, spec_draft_backend_sampling: true,
    spec_draft_threads: 0, spec_draft_threads_batch: 0,
    device: '', split_mode: '', tensor_split: '', main_gpu: 0,
    override_kv: '',
    host: '127.0.0.1', port: 8080, api_key: '', api_key_file: '',
    ssl_key_file: '', ssl_cert_file: '', path_prefix: '', api_prefix: '',
    no_ui: false, offline: false, ui_config_file: '', ui_config: '', ui_mcp_proxy: false,
    embedding: false, pooling: '', embd_normalize: 2, reranking: false,
    metrics: false, props: false, slots_enabled: true,
    slot_save_path: '', slot_prompt_similarity: 0.1, prefill_assistant: true,
    models_dir: '', models_preset: '', models_max: 4, models_autoload: true,
    mmproj_url: '', mmproj_auto: false, no_mmproj: false, no_mmproj_offload: false, image_min_tokens: 0, image_max_tokens: 0, mtmd_batch_max_tokens: 1024,
    tags: '', media_path: '', tools: '',
    n_predict: -1, ignore_eos: false, json_schema: '', json_schema_file: '',
    temp: 0.8, top_k: 40, top_p: 0.95, repeat_penalty: 1.0,
    seed: -1, min_p: 0.05, presence_penalty: 0,
    frequency_penalty: 0, repeat_last_n: 64,
    reverse_prompt: '', special: false, spm_infill: false, backend_sampling: false,
    mirostat: 0, mirostat_lr: 0.1, mirostat_ent: 5.0,
    xtc_probability: 0, xtc_threshold: 0.1,
    dynatemp_range: 0, dynatemp_exp: 1.0, typical_p: 1.0,
    dry_multiplier: 0, dry_base: 1.75,
    dry_allowed_length: 2, dry_penalty_last_n: -1,
    dry_sequence_breaker: '',
    adaptive_target: -1, adaptive_decay: 0.9, top_n_sigma: -1,
    logit_bias: '', samplers: '', sampler_seq: '',
    timeout: 3600, sleep_idle: -1, verbose: false, custom_args: [],
    rpc_servers: '', sse_ping_interval: 30, reuse_port: false, auto_start: false,
  }
}
