import type { InstanceConfig } from './types'

export function defaultInstanceConfig(): InstanceConfig {
  return {
    id: '', name: '', engine_id: '', model_path: '', alias: '',
    lora_path: '', mmproj_path: '', lora_init_without_apply: false,
    chat_template: '', chat_template_file: '', skip_chat_parsing: false,
    reasoning_format: '', reasoning_effort: '', reasoning: '',
    jinja: false, reasoning_budget: '', reasoning_budget_message: '',
    grammar_file: '', grammar: '',
    ctx_size: 4096, ctx_size_auto: false, gpu_layers: 99,
    threads: 0, batch_size: 2048, ubatch_size: 512, parallel: -1,
    cont_batching: false, cache_prompt: true, threads_batch: 0,
    threads_http: -1, keep: 0, cache_reuse: 0, cache_ram: 0,
    warmup: false, ctx_checkpoints: 32, checkpoint_min_step: 0,
    swa_full: false,
    rope_scaling: '', rope_scale: 0, rope_freq_base: 0, rope_freq_scale: 0,
    yarn_ext_factor: -1, yarn_attn_factor: 1, yarn_beta_slow: 0, yarn_beta_fast: 32,
    flash_attn: 'auto', moe_cpu_layers: 0, mlock: false,
    no_mmap: false, numa: false, context_shift: false,
    check_tensors: false, fit: false, kv_unified: false, cache_idle_slots: true,
    cache_type_k: '', cache_type_v: '',
    cache_type_draft_k: '', cache_type_draft_v: '',
    draft_model_path: '', draft_gpu_layers: 99, draft_tokens: 16,
    spec_draft_n_min: 0, spec_type: '',
    spec_draft_p_min: 0, spec_draft_p_split: 0.1, spec_draft_device: '',
    lookup_cache_static: '', lookup_cache_dynamic: '',
    device: '', split_mode: '', tensor_split: '', main_gpu: 0,
    override_kv: '',
    host: '127.0.0.1', port: 8080, api_key: '', api_key_file: '',
    ssl_key_file: '', ssl_cert_file: '', path_prefix: '', api_prefix: '',
    no_ui: false, ui_config_file: '',
    embedding: false, pooling: '', embd_normalize: 2, reranking: false,
    metrics: false, props: false, slots_enabled: true,
    slot_save_path: '', slot_prompt_similarity: 0.1, prefill_assistant: '',
    models_dir: '', models_preset: '', models_max: 4, models_autoload: false,
    mmproj_url: '', mmproj_auto: false, image_min_tokens: 0, image_max_tokens: 0,
    tags: '', media_path: '', tools: '',
    n_predict: -1, ignore_eos: false, json_schema: '',
    temp: 0.8, top_k: 40, top_p: 0.9, repeat_penalty: 1.1,
    seed: -1, min_p: 0.05, presence_penalty: 0,
    frequency_penalty: 0, repeat_last_n: 64,
    reverse_prompt: '', special: false, spm_infill: false, backend_sampling: false,
    mirostat: 0, mirostat_lr: 0, mirostat_ent: 0,
    xtc_probability: 0, xtc_threshold: 0,
    dynatemp_range: 0, dynatemp_exp: 0, typical_p: 1.0,
    dry_multiplier: 0, dry_base: 0,
    dry_allowed_length: 0, dry_penalty_last_n: 0,
    dry_sequence_breaker: '',
    adaptive_target: 0, adaptive_decay: 0, top_n_sigma: -1,
    logit_bias: '', samplers: '', sampler_seq: '',
    timeout: 600, sleep_idle: -1, verbose: false, custom_args: [],
  }
}
