import { expect, test } from '@playwright/test'

test.afterEach(async ({ page }) => { await expect(page.locator('html')).toHaveAttribute('data-tauri-mock-unhandled', '[]') })

for (const lang of ['zh-CN', 'en-US']) {
  test(`dashboard prioritizes resources and instance controls in ${lang}`, async ({ page }, testInfo) => {
    await page.addInitScript(language => { localStorage.setItem('lang', language); localStorage.setItem('lastTab', 'dashboard') }, lang)
    await page.setViewportSize({ width: 1920, height: 1400 })
    await page.goto('/?scenario=monitoring')
    const dashboard = page.locator('[data-guide="dashboard"]')
    const header = page.getByTestId('dashboard-header')
    const resources = page.getByTestId('dashboard-resources')
    const actions = page.getByTestId('dashboard-actions')
    const instances = page.getByTestId('dashboard-instances')
    const router = page.getByTestId('router-overview')
    await expect(resources).toContainText('44%')
    await expect(page.getByTestId('dashboard-secondary').getByTestId('router-overview')).toBeVisible()
    const boxes = await Promise.all([header, resources, actions, instances, router].map(el => el.boundingBox()))
    expect(boxes.every(Boolean)).toBe(true)
    const [h, r, a, i, route] = boxes.map(b => b!)
    expect(h.y + h.height).toBeLessThan(r.y)
    expect(r.y + r.height).toBeLessThan(a.y)
    expect(a.y + a.height).toBeLessThan(i.y)
    expect(route.x).toBeGreaterThan(i.x)
    expect(route.y).toBeGreaterThan(r.y + r.height)
    const themeButton = page.getByRole('button', { name: lang === 'zh-CN' ? '切换到明亮模式' : 'Switch to light mode' })
    await page.mouse.move(10, 10)
    await dashboard.screenshot({ path: testInfo.outputPath(`dashboard-${lang}-dark.png`) })
    await themeButton.click()
    await dashboard.screenshot({ path: testInfo.outputPath(`dashboard-${lang}-light.png`) })
    await page.setViewportSize({ width: 860, height: 1400 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    const narrowInstances = await instances.boundingBox()
    const narrowRouter = await router.boundingBox()
    expect(narrowRouter!.y).toBeGreaterThan(narrowInstances!.y + narrowInstances!.height)
    await page.screenshot({ path: testInfo.outputPath(`dashboard-${lang}-narrow.png`) })
    await router.getByRole('button').click()
    await expect(page.getByRole('tab', { name: lang === 'zh-CN' ? '路由配置' : 'Routing settings' })).toBeVisible()
  })
}
