import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('lang', 'zh-CN'); localStorage.setItem('lastTab', 'proxy') })
})
test.afterEach(async ({ page }) => {
  await expect(page.locator('html')).toHaveAttribute('data-tauri-mock-unhandled', '[]')
})
test('usage shows partial counts, coverage, cache and stable key filters', async ({ page }) => {
  await page.goto('/?scenario=proxy-routing')
  await page.getByRole('tab', { name: '使用统计' }).click()
  const panel = page.getByTestId('router-usage-panel')
  await expect(panel).toContainText('10,023')
  await expect(panel).toContainText('33.3%')
  await expect(panel).toContainText('80.0%')
  await expect(panel).toContainText('历史写入出现缺失或错误')
  await page.getByRole('combobox', { name: '使用统计 API Key' }).selectOption('key-b')
  await expect(panel).toContainText('0.0%')
  await expect(panel.getByRole('row').filter({ hasText: 'key-a' })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: '使用统计 API Key' }).locator('option[value="key-a"]')).toHaveCount(1)
  await page.getByRole('tab', { name: '路由配置' }).click()
  await expect(page.getByRole('heading', { name: 'API 兼容入口' })).toBeVisible()
})
test('usage exports a safe full summary and clears only after explicit confirmation', async ({ page }) => {
  await page.goto('/?scenario=proxy-routing')
  await page.getByRole('tab', { name: '使用统计' }).click()
  const exportButton = page.getByRole('button', { name: '导出当前汇总 CSV' })
  await expect(exportButton).toBeEnabled()
  const downloaded = page.waitForEvent('download')
  await exportButton.click()
  const download = await downloaded
  const stream = await download.createReadStream()
  const decoder = new TextDecoder()
  let csv = ''
  if (stream) for await (const part of stream) csv += decoder.decode(part as Uint8Array, { stream: true })
  csv += decoder.decode()
  expect(csv).toContain('"\'=Imported Client"')
  expect(csv).toContain('key-a')
  await page.getByRole('button', { name: '清除所选日期统计' }).click()
  await expect(page.getByRole('alert')).toContainText('所有 Key')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(exportButton).toBeEnabled()
  await page.getByRole('button', { name: '清除所选日期统计' }).click()
  await page.getByRole('button', { name: '确认清除' }).click()
  await expect(exportButton).toBeDisabled()
  await expect(page.getByText('所选范围暂无调用记录').first()).toBeVisible()
})
test('usage reports storage errors without presenting zero totals', async ({ page }) => {
  await page.goto('/?scenario=proxy-routing&usageError=1')
  await page.getByRole('tab', { name: '使用统计' }).click()
  await expect(page.getByRole('alert')).toContainText('Usage storage unavailable')
  await expect(page.getByRole('button', { name: '导出当前汇总 CSV' })).toBeDisabled()
})
test('usage layout supports a narrow dark viewport', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1040, height: 880 })
  await page.addInitScript(() => localStorage.setItem('theme', 'dark'))
  await page.goto('/?scenario=proxy-routing')
  await page.getByRole('tab', { name: '使用统计' }).click()
  await expect(page.getByRole('button', { name: '导出当前汇总 CSV' })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('usage-dark.png'), fullPage: true })
  await page.getByRole('heading', { name: '最近请求明细' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('usage-dark-details.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
