import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('lang', 'zh-CN'); localStorage.setItem('lastTab', 'proxy') })
})
test.afterEach(async ({ page }) => { await expect(page.locator('html')).toHaveAttribute('data-tauri-mock-unhandled', '[]') })

test('key concurrency, soft budgets and hard quotas survive save and reload', async ({ page }) => {
  await page.goto('/?scenario=proxy-routing')
  await page.getByRole('button', { name: '添加 API Key' }).click()
  await page.getByRole('checkbox', { name: '按 Key 轮转安排入场队列' }).check()
  await page.getByRole('spinbutton', { name: 'Key 并发上限' }).fill('2')
  await page.getByRole('spinbutton', { name: '每日 Token 软预算' }).fill('10000')
  await page.getByRole('spinbutton', { name: '每月 Token 软预算' }).fill('200000')
  await page.getByText('强制 Token 额度', { exact: true }).click()
  await page.getByRole('spinbutton', { name: '每日 Token 硬额度' }).fill('20000')
  await page.getByRole('spinbutton', { name: '每日 Token 硬额度' }).fill('')
  await expect(page.getByRole('spinbutton', { name: '每日 Token 硬额度' })).toBeVisible()
  await page.getByRole('spinbutton', { name: '每日 Token 硬额度' }).fill('20000')
  await page.getByRole('spinbutton', { name: '每月 Token 硬额度' }).fill('300000')
  await page.getByTestId('proxy-floating-save-button').click()
  await expect(page.getByText('代理配置已保存并生效')).toBeVisible()
  const saved = await page.evaluate(() => [...window.__TAURI_BROWSER_TEST__.calls].reverse().find(c => c.command === 'save_proxy_config')?.payload)
  expect(saved).toMatchObject({ config: { fair_queue_enabled: true, api_keys: [{ max_concurrent_requests: 2, daily_token_budget: 10000, monthly_token_budget: 200000, daily_token_limit: 20000, monthly_token_limit: 300000 }] } })
  await page.getByRole('tab', { name: '使用统计' }).click()
  await expect(page.getByTestId('router-management-panel')).toContainText('10,000')
  await page.getByRole('tab', { name: '路由配置' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Key 并发上限' })).toHaveValue('2')
  await expect(page.getByRole('spinbutton', { name: '每日 Token 硬额度' })).toHaveValue('20000')
  await expect(page.getByRole('spinbutton', { name: '每月 Token 硬额度' })).toHaveValue('300000')
  await expect(page.getByRole('checkbox', { name: '按 Key 轮转安排入场队列' })).toBeChecked()
})

test('quota ledger separates settled and held tokens from measured usage', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1200 })
  await page.goto('/?scenario=proxy-routing&usageManagement=quota')
  await page.getByRole('tab', { name: '使用统计' }).click()
  const panel = page.getByTestId('router-management-panel')
  const daily = panel.getByRole('meter', { name: 'WorkBuddy · 今日 · 强制 Token 额度', exact: true })
  await expect(daily).toHaveAttribute('aria-valuenow', '2000')
  await expect(daily).toHaveAttribute('aria-valuetext', '已结算 1,200, 待结算／保守占用 800, 可预留 1,000')
  await expect(panel.getByRole('meter', { name: 'WorkBuddy · 本月 · 强制 Token 额度', exact: true })).toHaveAttribute('aria-valuenow', '10000')
  await expect(panel).toContainText('11,000')
  await expect(panel).toContainText('不会自动当作零退款')
  await panel.screenshot({ path: testInfo.outputPath('quota-dark.png') })
  await page.getByRole('button', { name: '切换到明亮模式' }).click()
  await panel.screenshot({ path: testInfo.outputPath('quota-light.png') })
  await page.setViewportSize({ width: 860, height: 1500 })
  await panel.screenshot({ path: testInfo.outputPath('quota-narrow.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('performance filters and slow search preserve current-period budgets', async ({ page }, testInfo) => {
  await page.goto('/?scenario=proxy-routing&usageManagement=1')
  await page.getByRole('tab', { name: '使用统计' }).click()
  const performance = page.getByTestId('router-performance-panel')
  const management = page.getByTestId('router-management-panel')
  await expect(performance).toContainText('800 ms')
  await expect(management).toContainText('110.0%')
  await expect(management).toContainText('已达预算')
  await page.getByRole('button', { name: '今天', exact: true }).click()
  await expect(performance).toContainText('按小时')
  await performance.getByRole('combobox', { name: '耗时指标' }).selectOption('duration')
  await expect(performance).toContainText('P95 高于基线 2 倍')
  await performance.getByRole('combobox', { name: '分组性能' }).selectOption('instances')
  await expect(performance).toContainText('instance-one')
  await page.getByRole('combobox', { name: '慢请求筛选' }).selectOption('duration')
  await page.getByRole('spinbutton', { name: '至少耗时（毫秒）' }).fill('2000')
  await expect(page.getByTestId('router-request-history')).toContainText('所选范围暂无调用记录')
  await page.getByRole('combobox', { name: '调用类型' }).selectOption('count')
  await expect(performance).toContainText('当前筛选尚无性能样本')
  await expect(management).toContainText('110.0%')
  await page.getByRole('combobox', { name: '调用类型' }).selectOption('')
  await page.setViewportSize({ width: 1500, height: 1400 })
  await page.getByRole('button', { name: '切换到明亮模式' }).click()
  await expect(page.locator('html')).not.toHaveClass(/dark/)
  await performance.evaluate(el => { el.style.scrollMarginTop = '110px'; el.scrollIntoView({ block: 'start' }) })
  await page.mouse.move(10, 10)
  await performance.screenshot({ path: testInfo.outputPath('performance-light.png') })
  await page.getByRole('button', { name: '切换到深色模式' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await performance.screenshot({ path: testInfo.outputPath('performance-dark.png') })
  await page.setViewportSize({ width: 860, height: 900 })
  await management.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('management-narrow.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

for (const state of ['running', 'stopped']) {
  test(`current usage stays readable with five keys while ${state}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 1920, height: 1400 })
    await page.goto(`/?scenario=proxy-routing&usageManagement=layout${state === 'stopped' ? '-stopped' : ''}`)
    await page.getByRole('tab', { name: '使用统计' }).click()
    const panel = page.getByTestId('router-management-panel')
    await expect(panel.getByRole('listitem')).toHaveCount(5)
    await expect(panel).toContainText('33,828,766')
    await expect(panel.getByText('存在部分或未知用量，已知用量可能低于实际消耗。', { exact: true })).toHaveCount(1)
    await expect(panel.getByRole('img', { name: '用量不完整' })).toHaveCount(5)
    await expect(panel.getByRole('meter')).toHaveCount(4)
    const workBuddy = panel.getByRole('listitem').filter({ has: page.getByRole('heading', { name: 'WorkBuddy', exact: true }) })
    await expect(workBuddy.getByRole('meter')).toHaveCount(0)
    await expect(workBuddy.locator('dl[aria-label="WorkBuddy · 今日"]')).toContainText('0')
    const exceeded = panel.getByRole('meter', { name: 'Hermes · 今日 · 预算', exact: true })
    await expect(exceeded).toHaveAttribute('aria-valuenow', '300000')
    await expect(exceeded).toHaveAttribute('aria-valuetext', '323,580 / 300,000 Token (107.9%)')
    await expect(panel).toContainText('已达预算')
    if (state === 'stopped') {
      await expect(panel).toContainText('路由未运行')
      await expect(panel.locator('dl[aria-label$="实时并发"]')).toHaveCount(0)
      await expect(panel.getByTestId('router-concurrency-strip')).not.toContainText('—')
    } else {
      await expect(panel.locator('dl[aria-label$="实时并发"]')).toHaveCount(5)
      await expect(panel.locator('dl[aria-label="opencode · 实时并发"] dd')).toHaveText(['1', '2', '2'])
      await expect(workBuddy.locator('dl[aria-label$="实时并发"] dd')).toHaveText(['0', '0', '2'])
    }
    await panel.evaluate(el => { el.style.scrollMarginTop = '110px'; el.scrollIntoView({ block: 'start' }) })
    await page.mouse.move(10, 10)
    await panel.screenshot({ path: testInfo.outputPath(`management-${state}-dark.png`) })
    await page.getByRole('button', { name: '切换到明亮模式' }).click()
    await panel.screenshot({ path: testInfo.outputPath(`management-${state}-light.png`) })
    await page.setViewportSize({ width: 860, height: 1900 })
    await panel.evaluate(el => el.scrollIntoView({ block: 'start' }))
    await panel.screenshot({ path: testInfo.outputPath(`management-${state}-narrow.png`) })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    if (state === 'running') {
      await page.evaluate(() => { window.__TAURI_BROWSER_TEST__.failProxyStatus = true })
      await expect(panel.getByRole('alert')).toContainText('status unavailable', { timeout: 10_000 })
      await expect(panel.locator('dl[aria-label="opencode · 实时并发"] dd')).toHaveText(['—', '—', '—'])
      await expect(panel).toContainText('33,828,766')
    }
  })
}
